services:
  - type: web
    name: animals-picture-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
